<?php
/**
 * AddRequestsCreateExistingLocationRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (read-only)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AddRequestsCreateExistingLocationRequest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddRequestsCreateExistingLocationRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AddRequests:Create(ExistingLocation)Request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'existing_location_id' => 'string',
        'existing_location_account_id' => 'string',
        'skus' => 'string[]',
        'agreement_id' => 'int',
        'force_review' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'existing_location_id' => null,
        'existing_location_account_id' => null,
        'skus' => null,
        'agreement_id' => 'int32',
        'force_review' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'existing_location_id' => 'existingLocationId',
        'existing_location_account_id' => 'existingLocationAccountId',
        'skus' => 'skus',
        'agreement_id' => 'agreementId',
        'force_review' => 'forceReview'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'existing_location_id' => 'setExistingLocationId',
        'existing_location_account_id' => 'setExistingLocationAccountId',
        'skus' => 'setSkus',
        'agreement_id' => 'setAgreementId',
        'force_review' => 'setForceReview'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'existing_location_id' => 'getExistingLocationId',
        'existing_location_account_id' => 'getExistingLocationAccountId',
        'skus' => 'getSkus',
        'agreement_id' => 'getAgreementId',
        'force_review' => 'getForceReview'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['existing_location_id'] = isset($data['existing_location_id']) ? $data['existing_location_id'] : null;
        $this->container['existing_location_account_id'] = isset($data['existing_location_account_id']) ? $data['existing_location_account_id'] : null;
        $this->container['skus'] = isset($data['skus']) ? $data['skus'] : null;
        $this->container['agreement_id'] = isset($data['agreement_id']) ? $data['agreement_id'] : null;
        $this->container['force_review'] = isset($data['force_review']) ? $data['force_review'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['existing_location_id'] === null) {
            $invalidProperties[] = "'existing_location_id' can't be null";
        }
        if ($this->container['existing_location_account_id'] === null) {
            $invalidProperties[] = "'existing_location_account_id' can't be null";
        }
        if ($this->container['skus'] === null) {
            $invalidProperties[] = "'skus' can't be null";
        }
        if ($this->container['agreement_id'] === null) {
            $invalidProperties[] = "'agreement_id' can't be null";
        }
        if ($this->container['force_review'] === null) {
            $invalidProperties[] = "'force_review' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets existing_location_id
     *
     * @return string
     */
    public function getExistingLocationId()
    {
        return $this->container['existing_location_id'];
    }

    /**
     * Sets existing_location_id
     *
     * @param string $existing_location_id existing_location_id
     *
     * @return $this
     */
    public function setExistingLocationId($existing_location_id)
    {
        $this->container['existing_location_id'] = $existing_location_id;

        return $this;
    }

    /**
     * Gets existing_location_account_id
     *
     * @return string
     */
    public function getExistingLocationAccountId()
    {
        return $this->container['existing_location_account_id'];
    }

    /**
     * Sets existing_location_account_id
     *
     * @param string $existing_location_account_id existing_location_account_id
     *
     * @return $this
     */
    public function setExistingLocationAccountId($existing_location_account_id)
    {
        $this->container['existing_location_account_id'] = $existing_location_account_id;

        return $this;
    }

    /**
     * Gets skus
     *
     * @return string[]
     */
    public function getSkus()
    {
        return $this->container['skus'];
    }

    /**
     * Sets skus
     *
     * @param string[] $skus skus
     *
     * @return $this
     */
    public function setSkus($skus)
    {
        $this->container['skus'] = $skus;

        return $this;
    }

    /**
     * Gets agreement_id
     *
     * @return int
     */
    public function getAgreementId()
    {
        return $this->container['agreement_id'];
    }

    /**
     * Sets agreement_id
     *
     * @param int $agreement_id agreement_id
     *
     * @return $this
     */
    public function setAgreementId($agreement_id)
    {
        $this->container['agreement_id'] = $agreement_id;

        return $this;
    }

    /**
     * Gets force_review
     *
     * @return bool
     */
    public function getForceReview()
    {
        return $this->container['force_review'];
    }

    /**
     * Sets force_review
     *
     * @param bool $force_review force_review
     *
     * @return $this
     */
    public function setForceReview($force_review)
    {
        $this->container['force_review'] = $force_review;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


