<?php
/**
 * EntitiesUpdateLocationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (FINAL)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EntitiesUpdateLocationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description EntitiesUpdateLocationRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EntitiesUpdateLocationRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EntitiesUpdateLocationRequest"
     */
    public function testEntitiesUpdateLocationRequest()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
    }

    /**
     * Test attribute "additional_hours_text"
     */
    public function testPropertyAdditionalHoursText()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "address_hidden"
     */
    public function testPropertyAddressHidden()
    {
    }

    /**
     * Test attribute "alternate_names"
     */
    public function testPropertyAlternateNames()
    {
    }

    /**
     * Test attribute "alternate_phone"
     */
    public function testPropertyAlternatePhone()
    {
    }

    /**
     * Test attribute "alternate_websites"
     */
    public function testPropertyAlternateWebsites()
    {
    }

    /**
     * Test attribute "android_app_url"
     */
    public function testPropertyAndroidAppUrl()
    {
    }

    /**
     * Test attribute "associations"
     */
    public function testPropertyAssociations()
    {
    }

    /**
     * Test attribute "bios"
     */
    public function testPropertyBios()
    {
    }

    /**
     * Test attribute "brands"
     */
    public function testPropertyBrands()
    {
    }

    /**
     * Test attribute "calendars"
     */
    public function testPropertyCalendars()
    {
    }

    /**
     * Test attribute "closed"
     */
    public function testPropertyClosed()
    {
    }

    /**
     * Test attribute "custom_keywords"
     */
    public function testPropertyCustomKeywords()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "display_coordinate"
     */
    public function testPropertyDisplayCoordinate()
    {
    }

    /**
     * Test attribute "dropoff_coordinate"
     */
    public function testPropertyDropoffCoordinate()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "facebook_call_to_action"
     */
    public function testPropertyFacebookCallToAction()
    {
    }

    /**
     * Test attribute "facebook_cover_photo"
     */
    public function testPropertyFacebookCoverPhoto()
    {
    }

    /**
     * Test attribute "facebook_page_url"
     */
    public function testPropertyFacebookPageUrl()
    {
    }

    /**
     * Test attribute "facebook_profile_photo"
     */
    public function testPropertyFacebookProfilePhoto()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "featured_message"
     */
    public function testPropertyFeaturedMessage()
    {
    }

    /**
     * Test attribute "first_party_review_page"
     */
    public function testPropertyFirstPartyReviewPage()
    {
    }

    /**
     * Test attribute "google_cover_photo"
     */
    public function testPropertyGoogleCoverPhoto()
    {
    }

    /**
     * Test attribute "google_preferred_photo"
     */
    public function testPropertyGooglePreferredPhoto()
    {
    }

    /**
     * Test attribute "google_profile_photo"
     */
    public function testPropertyGoogleProfilePhoto()
    {
    }

    /**
     * Test attribute "google_website_override"
     */
    public function testPropertyGoogleWebsiteOverride()
    {
    }

    /**
     * Test attribute "holiday_hours_conversation_enabled"
     */
    public function testPropertyHolidayHoursConversationEnabled()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "instagram_handle"
     */
    public function testPropertyInstagramHandle()
    {
    }

    /**
     * Test attribute "ios_app_url"
     */
    public function testPropertyIosAppUrl()
    {
    }

    /**
     * Test attribute "iso_region_code"
     */
    public function testPropertyIsoRegionCode()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

    /**
     * Test attribute "local_phone"
     */
    public function testPropertyLocalPhone()
    {
    }

    /**
     * Test attribute "location_type"
     */
    public function testPropertyLocationType()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "main_phone"
     */
    public function testPropertyMainPhone()
    {
    }

    /**
     * Test attribute "menu_url"
     */
    public function testPropertyMenuUrl()
    {
    }

    /**
     * Test attribute "menus"
     */
    public function testPropertyMenus()
    {
    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "nudge_enabled"
     */
    public function testPropertyNudgeEnabled()
    {
    }

    /**
     * Test attribute "order_url"
     */
    public function testPropertyOrderUrl()
    {
    }

    /**
     * Test attribute "payment_options"
     */
    public function testPropertyPaymentOptions()
    {
    }

    /**
     * Test attribute "photo_gallery"
     */
    public function testPropertyPhotoGallery()
    {
    }

    /**
     * Test attribute "pickup_coordinate"
     */
    public function testPropertyPickupCoordinate()
    {
    }

    /**
     * Test attribute "price_range"
     */
    public function testPropertyPriceRange()
    {
    }

    /**
     * Test attribute "primary_conversation_contact"
     */
    public function testPropertyPrimaryConversationContact()
    {
    }

    /**
     * Test attribute "product_lists"
     */
    public function testPropertyProductLists()
    {
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
    }

    /**
     * Test attribute "rank_tracking_competitors"
     */
    public function testPropertyRankTrackingCompetitors()
    {
    }

    /**
     * Test attribute "rank_tracking_enabled"
     */
    public function testPropertyRankTrackingEnabled()
    {
    }

    /**
     * Test attribute "rank_tracking_frequency"
     */
    public function testPropertyRankTrackingFrequency()
    {
    }

    /**
     * Test attribute "rank_tracking_query_templates"
     */
    public function testPropertyRankTrackingQueryTemplates()
    {
    }

    /**
     * Test attribute "rank_tracking_sites"
     */
    public function testPropertyRankTrackingSites()
    {
    }

    /**
     * Test attribute "reservation_url"
     */
    public function testPropertyReservationUrl()
    {
    }

    /**
     * Test attribute "review_generation_url"
     */
    public function testPropertyReviewGenerationUrl()
    {
    }

    /**
     * Test attribute "review_response_conversation_enabled"
     */
    public function testPropertyReviewResponseConversationEnabled()
    {
    }

    /**
     * Test attribute "routable_coordinate"
     */
    public function testPropertyRoutableCoordinate()
    {
    }

    /**
     * Test attribute "service_area"
     */
    public function testPropertyServiceArea()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "specialities"
     */
    public function testPropertySpecialities()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "toll_free_phone"
     */
    public function testPropertyTollFreePhone()
    {
    }

    /**
     * Test attribute "tty_phone"
     */
    public function testPropertyTtyPhone()
    {
    }

    /**
     * Test attribute "twitter_handle"
     */
    public function testPropertyTwitterHandle()
    {
    }

    /**
     * Test attribute "uber_link"
     */
    public function testPropertyUberLink()
    {
    }

    /**
     * Test attribute "uber_trip_branding"
     */
    public function testPropertyUberTripBranding()
    {
    }

    /**
     * Test attribute "videos"
     */
    public function testPropertyVideos()
    {
    }

    /**
     * Test attribute "walkable_coordinate"
     */
    public function testPropertyWalkableCoordinate()
    {
    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {
    }

    /**
     * Test attribute "year_established"
     */
    public function testPropertyYearEstablished()
    {
    }

    /**
     * Test attribute "yext_display_coordinate"
     */
    public function testPropertyYextDisplayCoordinate()
    {
    }

    /**
     * Test attribute "yext_dropoff_coordinate"
     */
    public function testPropertyYextDropoffCoordinate()
    {
    }

    /**
     * Test attribute "yext_pickup_coordinate"
     */
    public function testPropertyYextPickupCoordinate()
    {
    }

    /**
     * Test attribute "yext_routable_coordinate"
     */
    public function testPropertyYextRoutableCoordinate()
    {
    }

    /**
     * Test attribute "yext_walkable_coordinate"
     */
    public function testPropertyYextWalkableCoordinate()
    {
    }
}
