<?php
/**
 * HoursTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (read-only)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HoursTest Class Doc Comment
 *
 * @category    Class
 * @description Hours
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HoursTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Hours"
     */
    public function testHours()
    {
    }

    /**
     * Test attribute "monday"
     */
    public function testPropertyMonday()
    {
    }

    /**
     * Test attribute "tuesday"
     */
    public function testPropertyTuesday()
    {
    }

    /**
     * Test attribute "wednesday"
     */
    public function testPropertyWednesday()
    {
    }

    /**
     * Test attribute "thursday"
     */
    public function testPropertyThursday()
    {
    }

    /**
     * Test attribute "friday"
     */
    public function testPropertyFriday()
    {
    }

    /**
     * Test attribute "saturday"
     */
    public function testPropertySaturday()
    {
    }

    /**
     * Test attribute "sunday"
     */
    public function testPropertySunday()
    {
    }

    /**
     * Test attribute "holiday_hours"
     */
    public function testPropertyHolidayHours()
    {
    }
}
