<?php
/**
 * NewLocationDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (FINAL)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NewLocationDataTest Class Doc Comment
 *
 * @category    Class
 * @description NewLocationData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewLocationDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewLocationData"
     */
    public function testNewLocationData()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "location_type"
     */
    public function testPropertyLocationType()
    {
    }

    /**
     * Test attribute "location_name"
     */
    public function testPropertyLocationName()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "middle_name"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "office_name"
     */
    public function testPropertyOfficeName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "npi"
     */
    public function testPropertyNpi()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "suppress_address"
     */
    public function testPropertySuppressAddress()
    {
    }

    /**
     * Test attribute "display_address"
     */
    public function testPropertyDisplayAddress()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "sublocality"
     */
    public function testPropertySublocality()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "service_area"
     */
    public function testPropertyServiceArea()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "is_phone_tracked"
     */
    public function testPropertyIsPhoneTracked()
    {
    }

    /**
     * Test attribute "local_phone"
     */
    public function testPropertyLocalPhone()
    {
    }

    /**
     * Test attribute "alternate_phone"
     */
    public function testPropertyAlternatePhone()
    {
    }

    /**
     * Test attribute "fax_phone"
     */
    public function testPropertyFaxPhone()
    {
    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "toll_free_phone"
     */
    public function testPropertyTollFreePhone()
    {
    }

    /**
     * Test attribute "tty_phone"
     */
    public function testPropertyTtyPhone()
    {
    }

    /**
     * Test attribute "category_ids"
     */
    public function testPropertyCategoryIds()
    {
    }

    /**
     * Test attribute "featured_message"
     */
    public function testPropertyFeaturedMessage()
    {
    }

    /**
     * Test attribute "featured_message_url"
     */
    public function testPropertyFeaturedMessageUrl()
    {
    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {
    }

    /**
     * Test attribute "display_website_url"
     */
    public function testPropertyDisplayWebsiteUrl()
    {
    }

    /**
     * Test attribute "reservation_url"
     */
    public function testPropertyReservationUrl()
    {
    }

    /**
     * Test attribute "display_reservation_url"
     */
    public function testPropertyDisplayReservationUrl()
    {
    }

    /**
     * Test attribute "menu_url"
     */
    public function testPropertyMenuUrl()
    {
    }

    /**
     * Test attribute "display_menu_url"
     */
    public function testPropertyDisplayMenuUrl()
    {
    }

    /**
     * Test attribute "order_url"
     */
    public function testPropertyOrderUrl()
    {
    }

    /**
     * Test attribute "display_order_url"
     */
    public function testPropertyDisplayOrderUrl()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "additional_hours_text"
     */
    public function testPropertyAdditionalHoursText()
    {
    }

    /**
     * Test attribute "holiday_hours"
     */
    public function testPropertyHolidayHours()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "conditions_treated"
     */
    public function testPropertyConditionsTreated()
    {
    }

    /**
     * Test attribute "certifications"
     */
    public function testPropertyCertifications()
    {
    }

    /**
     * Test attribute "education_list"
     */
    public function testPropertyEducationList()
    {
    }

    /**
     * Test attribute "degrees"
     */
    public function testPropertyDegrees()
    {
    }

    /**
     * Test attribute "admitting_hospitals"
     */
    public function testPropertyAdmittingHospitals()
    {
    }

    /**
     * Test attribute "accepting_new_patients"
     */
    public function testPropertyAcceptingNewPatients()
    {
    }

    /**
     * Test attribute "closed"
     */
    public function testPropertyClosed()
    {
    }

    /**
     * Test attribute "payment_options"
     */
    public function testPropertyPaymentOptions()
    {
    }

    /**
     * Test attribute "insurance_accepted"
     */
    public function testPropertyInsuranceAccepted()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "photos"
     */
    public function testPropertyPhotos()
    {
    }

    /**
     * Test attribute "headshot"
     */
    public function testPropertyHeadshot()
    {
    }

    /**
     * Test attribute "video_urls"
     */
    public function testPropertyVideoUrls()
    {
    }

    /**
     * Test attribute "instagram_handle"
     */
    public function testPropertyInstagramHandle()
    {
    }

    /**
     * Test attribute "twitter_handle"
     */
    public function testPropertyTwitterHandle()
    {
    }

    /**
     * Test attribute "google_website_override"
     */
    public function testPropertyGoogleWebsiteOverride()
    {
    }

    /**
     * Test attribute "google_cover_photo"
     */
    public function testPropertyGoogleCoverPhoto()
    {
    }

    /**
     * Test attribute "google_profile_photo"
     */
    public function testPropertyGoogleProfilePhoto()
    {
    }

    /**
     * Test attribute "google_preferred_photo"
     */
    public function testPropertyGooglePreferredPhoto()
    {
    }

    /**
     * Test attribute "google_attributes"
     */
    public function testPropertyGoogleAttributes()
    {
    }

    /**
     * Test attribute "facebook_page_url"
     */
    public function testPropertyFacebookPageUrl()
    {
    }

    /**
     * Test attribute "facebook_cover_photo"
     */
    public function testPropertyFacebookCoverPhoto()
    {
    }

    /**
     * Test attribute "facebook_profile_picture"
     */
    public function testPropertyFacebookProfilePicture()
    {
    }

    /**
     * Test attribute "uber_link_type"
     */
    public function testPropertyUberLinkType()
    {
    }

    /**
     * Test attribute "uber_link_text"
     */
    public function testPropertyUberLinkText()
    {
    }

    /**
     * Test attribute "uber_trip_branding_text"
     */
    public function testPropertyUberTripBrandingText()
    {
    }

    /**
     * Test attribute "uber_trip_branding_url"
     */
    public function testPropertyUberTripBrandingUrl()
    {
    }

    /**
     * Test attribute "uber_trip_branding_description"
     */
    public function testPropertyUberTripBrandingDescription()
    {
    }

    /**
     * Test attribute "uber_client_id"
     */
    public function testPropertyUberClientId()
    {
    }

    /**
     * Test attribute "year_established"
     */
    public function testPropertyYearEstablished()
    {
    }

    /**
     * Test attribute "display_lat"
     */
    public function testPropertyDisplayLat()
    {
    }

    /**
     * Test attribute "display_lng"
     */
    public function testPropertyDisplayLng()
    {
    }

    /**
     * Test attribute "routable_lat"
     */
    public function testPropertyRoutableLat()
    {
    }

    /**
     * Test attribute "routable_lng"
     */
    public function testPropertyRoutableLng()
    {
    }

    /**
     * Test attribute "walkable_lat"
     */
    public function testPropertyWalkableLat()
    {
    }

    /**
     * Test attribute "walkable_lng"
     */
    public function testPropertyWalkableLng()
    {
    }

    /**
     * Test attribute "pickup_lat"
     */
    public function testPropertyPickupLat()
    {
    }

    /**
     * Test attribute "pickup_lng"
     */
    public function testPropertyPickupLng()
    {
    }

    /**
     * Test attribute "dropoff_lat"
     */
    public function testPropertyDropoffLat()
    {
    }

    /**
     * Test attribute "dropoff_lng"
     */
    public function testPropertyDropoffLng()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "specialties"
     */
    public function testPropertySpecialties()
    {
    }

    /**
     * Test attribute "associations"
     */
    public function testPropertyAssociations()
    {
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "brands"
     */
    public function testPropertyBrands()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "menus_label"
     */
    public function testPropertyMenusLabel()
    {
    }

    /**
     * Test attribute "menu_ids"
     */
    public function testPropertyMenuIds()
    {
    }

    /**
     * Test attribute "bio_lists_label"
     */
    public function testPropertyBioListsLabel()
    {
    }

    /**
     * Test attribute "bio_list_ids"
     */
    public function testPropertyBioListIds()
    {
    }

    /**
     * Test attribute "product_lists_label"
     */
    public function testPropertyProductListsLabel()
    {
    }

    /**
     * Test attribute "product_list_ids"
     */
    public function testPropertyProductListIds()
    {
    }

    /**
     * Test attribute "event_lists_label"
     */
    public function testPropertyEventListsLabel()
    {
    }

    /**
     * Test attribute "event_list_ids"
     */
    public function testPropertyEventListIds()
    {
    }

    /**
     * Test attribute "folder_id"
     */
    public function testPropertyFolderId()
    {
    }

    /**
     * Test attribute "label_ids"
     */
    public function testPropertyLabelIds()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "intelligent_search_tracking_enabled"
     */
    public function testPropertyIntelligentSearchTrackingEnabled()
    {
    }

    /**
     * Test attribute "intelligent_search_tracking_frequency"
     */
    public function testPropertyIntelligentSearchTrackingFrequency()
    {
    }

    /**
     * Test attribute "location_keywords"
     */
    public function testPropertyLocationKeywords()
    {
    }

    /**
     * Test attribute "custom_keywords"
     */
    public function testPropertyCustomKeywords()
    {
    }

    /**
     * Test attribute "query_templates"
     */
    public function testPropertyQueryTemplates()
    {
    }

    /**
     * Test attribute "alternate_names"
     */
    public function testPropertyAlternateNames()
    {
    }

    /**
     * Test attribute "alternate_websites"
     */
    public function testPropertyAlternateWebsites()
    {
    }

    /**
     * Test attribute "competitors"
     */
    public function testPropertyCompetitors()
    {
    }

    /**
     * Test attribute "tracking_sites"
     */
    public function testPropertyTrackingSites()
    {
    }

    /**
     * Test attribute "is_cluster_primary"
     */
    public function testPropertyIsClusterPrimary()
    {
    }

    /**
     * Test attribute "attire"
     */
    public function testPropertyAttire()
    {
    }

    /**
     * Test attribute "price_range"
     */
    public function testPropertyPriceRange()
    {
    }

    /**
     * Test attribute "meals_served"
     */
    public function testPropertyMealsServed()
    {
    }

    /**
     * Test attribute "located_in"
     */
    public function testPropertyLocatedIn()
    {
    }

    /**
     * Test attribute "primary_contact"
     */
    public function testPropertyPrimaryContact()
    {
    }

    /**
     * Test attribute "review_response_conversation_enabled"
     */
    public function testPropertyReviewResponseConversationEnabled()
    {
    }

    /**
     * Test attribute "holiday_hours_confirmation_enabled"
     */
    public function testPropertyHolidayHoursConfirmationEnabled()
    {
    }
}
