<?php
/**
 * ValidationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (read-only)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ValidationTest Class Doc Comment
 *
 * @category    Class
 * @description Validation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ValidationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Validation"
     */
    public function testValidation()
    {
    }

    /**
     * Test attribute "min_char_length"
     */
    public function testPropertyMinCharLength()
    {
    }

    /**
     * Test attribute "max_char_length"
     */
    public function testPropertyMaxCharLength()
    {
    }

    /**
     * Test attribute "min_item_count"
     */
    public function testPropertyMinItemCount()
    {
    }

    /**
     * Test attribute "max_item_count"
     */
    public function testPropertyMaxItemCount()
    {
    }

    /**
     * Test attribute "min_value"
     */
    public function testPropertyMinValue()
    {
    }

    /**
     * Test attribute "max_value"
     */
    public function testPropertyMaxValue()
    {
    }

    /**
     * Test attribute "min_date"
     */
    public function testPropertyMinDate()
    {
    }

    /**
     * Test attribute "max_date"
     */
    public function testPropertyMaxDate()
    {
    }

    /**
     * Test attribute "aspect_ratio"
     */
    public function testPropertyAspectRatio()
    {
    }

    /**
     * Test attribute "min_width"
     */
    public function testPropertyMinWidth()
    {
    }

    /**
     * Test attribute "min_height"
     */
    public function testPropertyMinHeight()
    {
    }
}
