<?php
/**
 * EntitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (FINAL)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EntitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EntitiesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for entitiesGeosearch
     *
     * Entities: Geosearch.
     *
     */
    public function testEntitiesGeosearch()
    {
    }

    /**
     * Test case for entityLanguageProfilesGet
     *
     * Entity Language Profiles: Get.
     *
     */
    public function testEntityLanguageProfilesGet()
    {
    }

    /**
     * Test case for entityLanguageProfilesList
     *
     * Entity Language Profiles: List.
     *
     */
    public function testEntityLanguageProfilesList()
    {
    }

    /**
     * Test case for entityLanguageProfilesListAll
     *
     * Entity Language Profiles: List All.
     *
     */
    public function testEntityLanguageProfilesListAll()
    {
    }

    /**
     * Test case for getEntitiesGet
     *
     * Entities: Get.
     *
     */
    public function testGetEntitiesGet()
    {
    }

    /**
     * Test case for getEntitiesList
     *
     * Entities: List.
     *
     */
    public function testGetEntitiesList()
    {
    }
}
