<?php
/**
 * LocationsLegacyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * developer.yext.com (read-only)
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LocationsLegacyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationsLegacyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getLocationsGet
     *
     * Locations: Get.
     *
     */
    public function testGetLocationsGet()
    {
    }

    /**
     * Test case for getLocationsList
     *
     * Locations: List.
     *
     */
    public function testGetLocationsList()
    {
    }

    /**
     * Test case for languageProfilesGet
     *
     * Language Profiles: Get.
     *
     */
    public function testLanguageProfilesGet()
    {
    }

    /**
     * Test case for languageProfilesList
     *
     * Language Profiles: List.
     *
     */
    public function testLanguageProfilesList()
    {
    }

    /**
     * Test case for languageProfilesSchemaGet
     *
     * Language Profiles Schema: Get.
     *
     */
    public function testLanguageProfilesSchemaGet()
    {
    }

    /**
     * Test case for locationsCreate
     *
     * Locations Create.
     *
     */
    public function testLocationsCreate()
    {
    }

    /**
     * Test case for locationsGeoSearch
     *
     * Locations: GeoSearch.
     *
     */
    public function testLocationsGeoSearch()
    {
    }

    /**
     * Test case for locationsGet
     *
     * Locations: Get.
     *
     */
    public function testLocationsGet()
    {
    }

    /**
     * Test case for locationsList
     *
     * Locations: List.
     *
     */
    public function testLocationsList()
    {
    }

    /**
     * Test case for locationsSchemaGet
     *
     * Locations Schema: Get.
     *
     */
    public function testLocationsSchemaGet()
    {
    }

    /**
     * Test case for locationsSearch
     *
     * Locations: Search.
     *
     */
    public function testLocationsSearch()
    {
    }

    /**
     * Test case for locationsUpdate
     *
     * Locations: Update.
     *
     */
    public function testLocationsUpdate()
    {
    }
}
